// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHNorthwind.Model.Models;

public partial class DimDate
{
    public int DateKey { get; set; }

    public DateOnly Date { get; set; }

    public int? Year { get; set; }

    public int? Quarter { get; set; }

    public int? Month { get; set; }

    public int? Day { get; set; }

    public string MonthName { get; set; }

    public string DayName { get; set; }
}